# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Cognito Identity controller is a service controller for managing Cognito Identity resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Cognito Identity
description: |-
  Manage Amazon Cognito Identity resources in AWS from within your Kubernetes cluster.


  **About Amazon Cognito Identity**


  Amazon Cognito handles user authentication and authorization for your web and mobile apps. With user pools, you can easily
  and securely add sign-up and sign-in functionality to your apps. With identity pools (federated identities), your apps can 
  get temporary credentials that grant users access to specific AWS resources, whether the users are anonymous or are signed in.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: UserPool
  spec: '{}'
maintainers:
- name: "cognitoidentity maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Cognito Identity Developer Resources
  url: https://aws.amazon.com/cognito/dev-resources/
