// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AmbiguousRoleResolutionType string

const (
	AmbiguousRoleResolutionType_AuthenticatedRole AmbiguousRoleResolutionType = "AuthenticatedRole"
	AmbiguousRoleResolutionType_Deny              AmbiguousRoleResolutionType = "Deny"
)

type ErrorCode string

const (
	ErrorCode_AccessDenied        ErrorCode = "AccessDenied"
	ErrorCode_InternalServerError ErrorCode = "InternalServerError"
)

type MappingRuleMatchType string

const (
	MappingRuleMatchType_Equals     MappingRuleMatchType = "Equals"
	MappingRuleMatchType_Contains   MappingRuleMatchType = "Contains"
	MappingRuleMatchType_StartsWith MappingRuleMatchType = "StartsWith"
	MappingRuleMatchType_NotEqual   MappingRuleMatchType = "NotEqual"
)

type RoleMappingType string

const (
	RoleMappingType_Token RoleMappingType = "Token"
	RoleMappingType_Rules RoleMappingType = "Rules"
)
